<?php

class dipoleDashletsPlugin extends PMPlugin
{
  private $dashletsUids;
  
  public function dipoleDashletsPlugin($sNamespace, $sFilename = null)
  {
    $res = parent::PMPlugin($sNamespace, $sFilename);
    $this->sFriendlyName = "dipoleDashlets Plugin";
    $this->sDescription  = "Autogenerated plugin for class dipoleDashlets";
    $this->sPluginFolder = "dipoleDashlets";
    $this->sSetupPage    = "setup";
    $this->iVersion      = "1.0.0";
    //$this->iPMVersion    = 2425;
    $this->aWorkspaces   = null;
    //$this->aWorkspaces = array("os");
    
    
    $this->dashletsUids = array(
      array("DAS_UID" => "4521678215de5134439da58020371216",
            "DAS_CLASS" => "dashletdipoleDashlets",
            "DAS_TITLE" => "Dashlet dipoleDashlets",
            "DAS_DESCRIPTION" => "Dashlet dipoleDashlets",
            "DAS_VERSION" => "1.0",
            "DAS_CREATE_DATE" => date("Y-m-d"),
            "DAS_UPDATE_DATE" => date("Y-m-d"))
    );
    
    
    return $res;
  }

  public function setup()
  {
    $this->registerMenu("processmaker", "menudipoleDashlets.php");
    $this->registerMenu("cases", "menuCasesdipoleDashlets.php");
    $this->registerStep("5801500915de5133e02ff44016240300", "stepdipoleDashletsApplication", "dipoleDashlets external step");
    $this->registerPmFunction();
    
    $this->registerDashlets();
  }

  public function install()
  {
    $RBAC = RBAC::getSingleton() ;
    $RBAC->initRBAC();
    $roleData = array();
    $roleData["ROL_UID"] = G::GenerateUniqueId();
    $roleData["ROL_PARENT"] = "";
    $roleData["ROL_SYSTEM"] = "00000000000000000000000000000002";
    $roleData["ROL_CODE"] = "PROCESSMAKER_DIPOLEDASHLETS";
    $roleData["ROL_CREATE_DATE"] = date("Y-m-d H:i:s");
    $roleData["ROL_UPDATE_DATE"] = date("Y-m-d H:i:s");
    $roleData["ROL_STATUS"] = "1";
    $RBAC->createRole($roleData);
    $RBAC->createPermision("PM_DIPOLEDASHLETS");
  }
  
  public function enable()
  {
    $this->dashletInsert();
  }

  public function disable()
  {
    $this->dashletDelete();
  }
  
  public function dashletInsert()
  {

    
    $connection = Propel::getConnection(DashletPeer::DATABASE_NAME);
    
    foreach ($this->dashletsUids as $dashletData) {
      $dashlet = new Dashlet();
      
      if (is_null($dashlet->load($dashletData["DAS_UID"]))) {
        $dashlet->fromArray($dashletData, BasePeer::TYPE_FIELDNAME);
        $connection->begin();
        $dashlet->save();
        $connection->commit();
      }
    }
  }
  
  public function dashletDelete()
  {

    
    foreach ($this->dashletsUids as $dashletData) {
      $criteria = new Criteria("workflow");
      $criteria->add(DashletPeer::DAS_UID, $dashletData["DAS_UID"]);
      DashletPeer::doDelete($criteria);
    }
  }
}

$oPluginRegistry = PMPluginRegistry::getSingleton();
$oPluginRegistry->registerPlugin("dipoleDashlets", __FILE__);
